name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    steps:
    - name: Checkout repo ${{ matrix.os }}
      uses: actions/checkout@v3
    - name: Setup Docker Buildx ${{ matrix.os }}
      uses: docker/setup-buildx-action@v2
    - name: Build and push ${{ matrix.os }}
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}
