name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    steps:
    - name: Checkout repo ${{ matrix.os }}
      uses: actions/checkout@v3

    - name: Setup Docker Buildx ${{ matrix.os }}
      uses: docker/setup-buildx-action@v2

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ghcr.io ${{ matrix.os }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.REGISTRY_TOKEN }}

    - name: Build and push ${{ matrix.os }}
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}
